version: '3.8'

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - '.:/app'
      - '/app/node_modules'  